services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      APP_PORT: 3000
      POSTGRES_USER: atropos_task_service
      POSTGRES_PASSWORD: geneva
      POSTGRES_DB: atropos_tasks
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
    command: npm start
    working_dir: /app

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: atropos_task_service
      POSTGRES_PASSWORD: geneva
      POSTGRES_DB: atropos_tasks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
